# This is a basic workflow to help you get started with Actions

name: Get NHSN Snapshot

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#permissions:  # Was not really needed. Enough that the actions have write permission in the repo.
#  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get_nhsn_snapshot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Get current date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
          # cache: 'pip' # (optional) caching pip dependencies
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create datasets directory
        run: mkdir -p datasets/nhsn_weekly_jurisdiction

      - name: Run the script
        run: |
            echo "Triggered event: ${{github.event.action}}"
            echo "Running python script to fetch NHSN data"
            python get_nhsn_snapshot.py --release latest

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: datasets/nhsn_weekly_jurisdiction  # Select which files to commit
          message: "Save NHSN snapshot"
#          default_author: github_actor
          push: true

