# This is a basic workflow to help you get started with Actions

name: Hello Actions

# Controls when the workflow will run
on:
  # # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#permissions:  # Was not really needed. Enough that the actions have write permission in the repo.
#  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run_hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
          # cache: 'pip' # (optional) caching pip dependencies
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create datasets directory
        run: mkdir -p datasets

      - name: Run the script
        run: |
            echo "Running your python script:"
            python hello.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: datasets  # Select which files to commit
          message: "Commit outputs from `hello.py`"
#          default_author: github_actor
          push: true

